backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "Aktuality" # Used in the UI
    folder: "src/pages/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "Titulek", widget: "string"}
      - {label: "Publish Date", name: "Datum vytvoření", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
